### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by jgallen23**
- confi
- logging
- method-loader
- route-loader

everything else should be added by the app that's using it.  One thing I'd like to bring back is the method cli stuff, but we should pull that into a plugin. Also updated all dependencies.

@ecwillis @dawnerd

### CODE REVIEW

**Comment by jgallen23** [comment]
for the template and asset stuff, I think we should make a hapi-www plugin that handles that.

**Comment by dawnerd** [comment]
Ran into an issue starting rapptor without the cli.

```
/Users/troywhiteley/Projects/openhaunt/node_modules/rapptor/index.js:9
    const projectConfig = options.configPath || `${options.cwd}/conf`;
                                 ^

TypeError: Cannot read property 'configPath' of undefined
    at new Rapptor (/Users/troywhiteley/Projects/openhaunt/node_modules/rapptor/index.js:9:34)
    at Object.<anonymous> (/Users/troywhiteley/Projects/openhaunt/index.js:4:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

Switched over to using the cli and it worked fine.

**Comment by jgallen23** [comment]
ahh, needs this.options

**Comment by jgallen23** [comment]
@ecwillis @dawnerd  this is ready to review

**Pull request merged**
